# Site settings
title: Santiago Fraga
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Santiago Fraga
user_description: I'm a Software Engineer from Spain, always searching for the next challenge; Lately I have been immersed in blockchain, smart contract and cybersecurity.
user_title: Software Engineer
email: test@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
